# IMPORT LIBRARY

In [1]:
import tensorflow as tf
import numpy as np

# Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=4)
print(random_tensor)

tf.Tensor(
[[ 0.29629603 -0.03141323 -0.05471061  0.03763179  2.564978  ]
 [-0.6494583  -0.6845234   0.43688074  1.4897977  -0.2399326 ]
 [ 0.04981674  0.41748446  0.11580934  0.8780719   0.27877015]
 [-1.5849335   1.1436394   1.0639356   1.1304685   1.3247743 ]
 [ 2.1117373  -0.863544   -1.8417858   0.4749224  -0.9902795 ]], shape=(5, 5), dtype=float32)


# Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [3]:
prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 101]]

prime_tensor = tf.constant(prime, dtype=tf.float32)
print(prime_tensor)

tf.Tensor(
[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]], shape=(5, 5), dtype=float32)


# Tampilkan dimensi dari kedua variable tersebut

In [4]:
#random tensor
print(random_tensor.shape)
print(type(random_tensor))

(5, 5)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
#prime tensor
print(prime_tensor.shape)
print(type(prime_tensor))

(5, 5)
<class 'tensorflow.python.framework.ops.EagerTensor'>


# Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [6]:
# Penjumlahan
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[  2.2962961   2.9685867   4.9452896   7.037632   13.564978 ]
 [ 12.350542   16.315477   19.43688    24.489798   28.760067 ]
 [ 31.049816   37.417484   41.11581    43.87807    47.27877  ]
 [ 51.415066   60.14364    62.063934   72.13047    74.324776 ]
 [ 81.11174    82.13646    87.15821    97.47492   100.00972  ]], shape=(5, 5), dtype=float32)


In [7]:
# Pengurangan
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[  -1.703704    -3.0314133   -5.0547104   -6.962368    -8.435022 ]
 [ -13.649458   -17.684523   -18.56312    -21.510202   -29.239933 ]
 [ -30.950184   -36.582516   -40.88419    -42.12193    -46.72123  ]
 [ -54.584934   -57.85636    -59.936066   -69.86953    -71.675224 ]
 [ -76.88826    -83.86354    -90.84179    -96.52508   -101.99028  ]], shape=(5, 5), dtype=float32)


In [8]:
# Perkalian
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[ 5.9259206e-01 -9.4239704e-02 -2.7355304e-01  2.6342255e-01
   2.8214756e+01]
 [-8.4429579e+00 -1.1636898e+01  8.3007336e+00  3.4265347e+01
  -6.9580455e+00]
 [ 1.5443188e+00  1.5446925e+01  4.7481828e+00  3.7757092e+01
   1.3102197e+01]
 [-8.4001480e+01  6.7474724e+01  6.4900070e+01  8.0263260e+01
   9.6708519e+01]
 [ 1.6682724e+02 -7.1674149e+01 -1.6391893e+02  4.6067471e+01
  -1.0001823e+02]], shape=(5, 5), dtype=float32)


In [9]:
# Pembagian
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[ 0.14814802 -0.01047108 -0.01094212  0.00537597  0.23317981]
 [-0.04995833 -0.04026608  0.02299372  0.06477381 -0.00827354]
 [ 0.00160699  0.01128336  0.00282462  0.02042028  0.00593128]
 [-0.02990441  0.01938372  0.01744157  0.01592209  0.01814759]
 [ 0.02673085 -0.01040414 -0.02069422  0.00489611 -0.00980475]], shape=(5, 5), dtype=float32)


In [10]:
# Pangkat
print(tf.pow(prime_tensor,random_tensor))

tf.Tensor(
[[1.22798765e+00 9.66077745e-01 9.15712059e-01 1.07597589e+00
  4.68974487e+02]
 [1.89034149e-01 1.43790081e-01 3.61961865e+00 1.06831421e+02
  4.45782542e-01]
 [1.18657386e+00 4.51543760e+00 1.53735948e+00 2.71833363e+01
  2.92503428e+00]
 [1.84985367e-03 1.05978119e+02 7.93370514e+01 1.23819550e+02
  2.94091309e+02]
 [1.01692705e+04 2.20186990e-02 2.56827305e-04 8.78137207e+00
  1.03552751e-02]], shape=(5, 5), dtype=float32)


# Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [11]:
# Max
print(tf.reduce_max(random_tensor).numpy())

2.564978


In [12]:
# Min
print(tf.reduce_min(random_tensor).numpy())

-1.8417858


# Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [13]:
# Kolom = 0
print(tf.concat([random_tensor, prime_tensor], axis=0))

tf.Tensor(
[[ 2.9629603e-01 -3.1413235e-02 -5.4710608e-02  3.7631791e-02
   2.5649779e+00]
 [-6.4945829e-01 -6.8452340e-01  4.3688074e-01  1.4897977e+00
  -2.3993260e-01]
 [ 4.9816735e-02  4.1748446e-01  1.1580934e-01  8.7807190e-01
   2.7877015e-01]
 [-1.5849335e+00  1.1436394e+00  1.0639356e+00  1.1304685e+00
   1.3247743e+00]
 [ 2.1117373e+00 -8.6354399e-01 -1.8417858e+00  4.7492239e-01
  -9.9027950e-01]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  7.1000000e+01
   7.3000000e+01]
 [ 7.9000000e+01  8.3000000e+01  8.9000000e+01  9.7000000e+01
   1.0100000e+02]], shape=(10, 5), dtype=float32)


In [14]:
# Kolom = 1
print(tf.concat([random_tensor, prime_tensor], axis=1))

tf.Tensor(
[[ 2.9629603e-01 -3.1413235e-02 -5.4710608e-02  3.7631791e-02
   2.5649779e+00  2.0000000e+00  3.0000000e+00  5.0000000e+00
   7.0000000e+00  1.1000000e+01]
 [-6.4945829e-01 -6.8452340e-01  4.3688074e-01  1.4897977e+00
  -2.3993260e-01  1.3000000e+01  1.7000000e+01  1.9000000e+01
   2.3000000e+01  2.9000000e+01]
 [ 4.9816735e-02  4.1748446e-01  1.1580934e-01  8.7807190e-01
   2.7877015e-01  3.1000000e+01  3.7000000e+01  4.1000000e+01
   4.3000000e+01  4.7000000e+01]
 [-1.5849335e+00  1.1436394e+00  1.0639356e+00  1.1304685e+00
   1.3247743e+00  5.3000000e+01  5.9000000e+01  6.1000000e+01
   7.1000000e+01  7.3000000e+01]
 [ 2.1117373e+00 -8.6354399e-01 -1.8417858e+00  4.7492239e-01
  -9.9027950e-01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01  1.0100000e+02]], shape=(5, 10), dtype=float32)


# Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [15]:
print(tf.sort(random_tensor, direction='DESCENDING'))

tf.Tensor(
[[ 2.564978    0.29629603  0.03763179 -0.03141323 -0.05471061]
 [ 1.4897977   0.43688074 -0.2399326  -0.6494583  -0.6845234 ]
 [ 0.8780719   0.41748446  0.27877015  0.11580934  0.04981674]
 [ 1.3247743   1.1436394   1.1304685   1.0639356  -1.5849335 ]
 [ 2.1117373   0.4749224  -0.863544   -0.9902795  -1.8417858 ]], shape=(5, 5), dtype=float32)


In [16]:
print(tf.sort(prime_tensor, direction='DESCENDING'))

tf.Tensor(
[[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]], shape=(5, 5), dtype=float32)
